Play computer
mihaitzzza/nt-team1-tic-tac-toe pull request #2
Opened 2021-02-22 19:46 UTC by Fiphee

Play versus computer with 3 selectable difficulties

2021-02-23 08:44 UTC, mihaitzzza requested changes

2021-02-23 08:44 UTC, mihaitzzza commented on game/board.py
> +    new_board = [x[:] for x in board]
Please use `copy.deepcopy()` discuss yesterday, it's a bit cleaner and easier to read.

2021-02-23 08:44 UTC, mihaitzzza commented on game/menus.py
> +def main_menu():
I suppose here's a warning for two empty lines expected :)

2021-02-23 08:44 UTC, mihaitzzza commented on game/menus.py
> +    while True:
`while selection != '2'`

2021-02-23 08:44 UTC, mihaitzzza commented on game/menus.py
> +        elif selection == '2':
Not needed `else` branch and manual `break` if using the right condition in the `while` loop.

2021-02-23 08:44 UTC, mihaitzzza commented on game/menus.py
> +    while on_play_menu:
`while selection != '3'`

2021-02-23 08:44 UTC, mihaitzzza commented on game/menus.py
> +            on_play_menu = False
I would add a `break` here instead of using the `on_play_menu` variable.

2021-02-23 08:44 UTC, mihaitzzza commented on game/menus.py
> +            on_play_menu = False
I would add a `break` here instead of using the `on_play_menu` variable.

2021-02-23 08:44 UTC, mihaitzzza commented on game/menus.py
> +        elif selection == '3':
Remove these lines by simply change the condition on `while` loop.

2021-02-23 08:44 UTC, mihaitzzza commented on game/menus.py
> +    while on_difficulty_menu:
Same as the `while` comments from `play_menu` function.

2021-02-23 08:44 UTC, mihaitzzza commented on game/modes.py
> +def play(cpu=False):
Please use `None` as default. You're sending a `string` from the `menu` functions, but you're defaulting to a `boolean`. I know Python allow you to change the type of a variable, but try to avoid it.

2021-02-23 08:44 UTC, mihaitzzza commented on game/modes.py
> +    while True:
`while not is_correct_choice`

2021-02-23 08:44 UTC, mihaitzzza commented on game/modes.py
> +            return is_correct_choice, choice
Using the `while` condition from my comment, you can get rid of the `else` branch and do the return outside the `while` loop - code simplification.

2021-02-23 08:44 UTC, mihaitzzza commented on game/modes.py
> +                raise ValueError()
Add a message to explain the error. `Not an available choice` or something.

2021-02-23 08:44 UTC, mihaitzzza commented on game/modes.py
> +
Remove not needed extra line.

2021-02-23 08:44 UTC, mihaitzzza commented on game/modes.py
> +    elif difficulty == 'medium':
What about the `'hard'` one? :) What happens if I select the HARD difficulty?

2021-02-23 08:44 UTC, mihaitzzza commented on game/modes.py
> +def _found_blocking_cell(board_matrix, available_options):
`_find_blocking_cell` or `_get_blocking_cell`. Don't use `found`. The functions/methods should express actions (present time).
Also just realize this function duplicates 99% of the previous one. The only difference is the `'x'` or `'o'` parameter sent to `set_choice`. Please refactor the previous function to allow another parameter and don't duplicate the code.

2021-02-23 08:44 UTC, mihaitzzza commented on game/modes.py
> +def _found_winning_cell(board_matrix, available_options):
`_find_winning_cell` or `_get_winning_cell`. Don't use `found`. The functions/methods should express actions (present time).

2021-02-23 08:44 UTC, mihaitzzza commented on game/modes.py
> +        check_spots = [x[:] for x in board_matrix]
Please use `copy.deepecopy()` discussed yesterday. It's more clear and easier to read. Also the variable name is not suggestive. What does actually `check_spots` mean ... isn't it a copy of the board?

2021-02-23 08:44 UTC, mihaitzzza commented on game/modes.py
> +        new_board = set_choice(check_spots, choice, 'o')
`set` express setting something, not returning something.

2021-02-23 08:44 UTC, mihaitzzza commented on game/modes.py
> +            return True, choice
I would init `is_won = False` (and `choice = None`) outside the `for` and just `break` the `for` if the game is won.

2021-02-23 08:44 UTC, mihaitzzza commented on game/modes.py
> +    return False, None
`return is_won, choice`

2021-02-23 08:44 UTC, mihaitzzza commented on game/modes.py
> +    corners = [x for x in available_options if x % 2 == 1 and x != 5]
Don't compute the `corners` here since you're using them way lower. It's kind of confusing. You either init all the things in the top of the functions, either right when you need them.

2021-02-23 08:44 UTC, mihaitzzza commented on game/modes.py
> +
Too much empty lines. One is enough.

2021-02-23 08:44 UTC, mihaitzzza commented on game/modes.py
> +    if last_move % 2 == 1 and last_move != 5:
I need you to explain me this `if`s :) You can send a message on the team's Slack channel.

2021-02-23 08:44 UTC, mihaitzzza commented on game/modes.py
> +    print('Game Over!')
Since you have a menu and this function is JUST running a game, the function who called this should account for winning states and stuff like this. So all the code from L142 to the end of the function should "go away".

2021-02-23 08:44 UTC, mihaitzzza commented on game/player.py
>          sign = 'o'
Please move this on top of the `if not cpu` to be more clear why you're doing `else` instead of directly `elif not cpu`.

2021-02-23 08:44 UTC, mihaitzzza commented on main.py
> +
Why are you touching files that you should not? :)

2021-02-23 18:34 UTC, Fiphee commented on main.py
> +
It needed an extra space after imports. That's my post-excuse cel putin :))

2021-02-28 15:39 UTC, mihaitzzza requested changes

2021-02-28 15:39 UTC, mihaitzzza commented on game/menus.py
> +    selection = 0
You either init with `None` or empty string. Stop changeing variable type.

2021-02-28 15:39 UTC, mihaitzzza commented on game/modes.py
> +        return random.choice(available_options)
Is this because `corners` can be an empty array? If so, I found easier to use `return random.choice(corners or available_options)`.

2021-03-02 17:47 UTC, PixLix1 commented on game/modes.py
> +    '''
PEP: Triple double-quoted strings should be used for docstrings.

I would rephrase the comment as it is a bit too long and becomes hard to follow :)

```suggestion
    '''
    Creates a copy of the current state of the board and tries all the available options with the sign argument.
    Checks if any choice wins.
    Returns True or False if there is a winning choice, along with the the choice itself.
    '''
```

2021-03-02 17:52 UTC, PixLix1 commented on game/modes.py
> +def _find_winning_cell(board_matrix, available_options, sign):
Is there a specific reason for using an underscore in the beginning of the function's name?
I think it should be something like:
```suggestion
def find_winning_cell(board_matrix, available_options, sign):
```

2021-03-02 18:05 UTC, PixLix1 commented on game/modes.py
> +    '''
1. naming convention (unless there is another reason for using underscore at the beginning of the function's name)
2. PEP warning for triple double-quotes

2021-03-02 18:06 UTC, PixLix1 commented on game/modes.py
> +    '''
1. naming convention (unless there is another reason for using underscore at the beginning of the function's name)
2. PEP warning for triple double-quotes

```suggestion
def _computer_move(available_options, board_matrix, last_move, difficulty):
    """
    difficulties: 'easy' picks randomly from the available options
    'medium' checks to for a winning move for itself, or blocks player from winning on next move. 
    if there is no winning move next move, it chooses a random available option
    'hard' checks for win or blocks player like the medium difficulty, but also strategically picks a move
    if there is no winning or blocking move
    
    return:: choice
    """
```

2021-03-02 18:09 UTC, PixLix1 commented on game/modes.py
> +def _player_move(board_matrix, available_options):
naming convention
```suggestion
def player_move(board_matrix, available_options):
```

2021-03-08 09:16 UTC, mihaitzzza approved these changes

2021-03-08 15:53 UTC, merged